AddSeller:
  path: /seller
  controller: App\Infrastructure\Controller\SellerController::add
  methods: POST

DeleteSeller:
  path: /seller
  controller: App\Infrastructure\Controller\SellerController::delete
  methods: DELETE

AddProduct:
  path: /product
  controller: App\Infrastructure\Controller\ProductController::add
  methods: POST
