AddSeller:
  path: /seller
  controller: App\Infrastructure\Controller\SellerController::add
  methods: POST

DeleteSeller:
  path: /seller
  controller: App\Infrastructure\Controller\SellerController::delete
  methods: DELETE

AddProduct:
  path: /product
  controller: App\Infrastructure\Controller\ProductController::add
  methods: POST

DeleteProduct:
  path: /product
  controller: App\Infrastructure\Controller\ProductController::delete
  methods: DELETE

AddUser:
  path: /user
  controller: App\Infrastructure\Controller\UserController::add
  methods: POST

AddToCart:
  path: /cart
  controller: App\Infrastructure\Controller\CartController::add
  methods: POST

DeleteProductFromCart:
  path: /cart
  controller: App\Infrastructure\Controller\CartController::delete
  methods: DELETE

GetTotalAmountFromCart:
  path: /cart
  controller: App\Infrastructure\Controller\CartController::getAmount
  methods: GET

ModifyAmountProduct:
  path: /product/modifyAmount
  controller: App\Infrastructure\Controller\ProductController::modifyAmount
  methods: PUT



